apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: Automate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend-pod
      namespace: Automate
      labels:
        app: frontend
    spec:
      containers:
      - name: chatapp-frontend
        image: anu548/chatapp-frontend:latest
        ports:
        - containerPort: 80
        env:
         - name: NODE_ENV
           value: production
         - name: CUSTOMER_CODE
           value: "XYZ999"
         - name: CURRENT_VERSION
           value: "2.5"
         - name: TARGET_VERSION
           value: "2.5"