apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
   namespace: automate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: nginx:latest   # you can change this later
          ports:
            - containerPort: 80
          env:
            - name: CUSTOMER_CODE
              value: "ABC123"
            - name: CURRENT_VERSION
              value: "1.0.0"
            - name: TARGET_VERSION
              value: "1.0.0"